Repository BChip/SVSUCardinalVolunteer, pull requests merged in 2018-10, with the labels that each got.

#2 View postings - design overhaul
  .vscode/settings.json
  client/src/components/postings.js
  client/src/style/style.css
Labels: frontend

#3 removed rsvp endpoint and generated new docs
  server/DOCS.md
  server/src/api/index.js
  server/src/api/posting/index.test.js
  server/src/api/posting/model.js
  server/src/api/posting/model.test.js
  server/src/api/rsvp/controller.js
  server/src/api/rsvp/index.js
  server/src/api/rsvp/index.test.js
  server/src/api/rsvp/model.js
  server/src/api/rsvp/model.test.js
Labels: backend

#7 Dev1
  client/package-lock.json
  client/public/favicon.png
  client/public/index.html
  client/public/manifest.json
  client/src/actions/index.js
  client/src/actions/types.js
  client/src/components/app.js
  client/src/components/auth/signin.js
  client/src/components/auth/signout.js
  client/src/components/auth/signup.js
  client/src/components/header.js
  client/src/components/postcreate.js
  client/src/components/postings.js
  client/src/components/welcome.js
  client/src/index.js
  client/src/reducers/postings.js
  client/src/routes/index.js
  client/src/style/style.css
  client/yarn.lock
  server/yarn.lock
  yarn.lock
Labels: frontend

#9 Dev1
  client/src/actions/index.js
  client/src/actions/types.js
  client/src/components/auth/signin.js
  client/src/components/auth/signup.js
  client/src/components/header.js
  client/src/components/postcreate.js
  client/src/reducers/auth.js
Labels: bug, enhancement, frontend
